### ISSUE TITLE
[Bug] 百度翻译没有效果

### ISSUE THREAD

**Issue by 399294508** [javtube/jellyfin-plugin-javtube#10]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

最新

### JavTube Server Version

最新

### Description

请问是接入百度 机器翻译 这个API接口的数值吗？为什么填写了以后影片刷新元数据并没有任何作用呢

**Comment by xjasonlyu** [comment]
具体配置说明一下，翻译模式选的是什么之类的。

**Comment by 399294508** [comment]
> 具体配置说明一下，翻译模式选的是什么类的。

翻译模式选的全部，翻译引擎是百度

**Comment by xjasonlyu** [comment]
> 翻译模式选的全部，翻译引擎是百度

其他数据呢，你没说怎么填的API Key，也没有带上Emby报错日志，很难知道是哪里出的问题的。

**Comment by xxxml** [comment]
API 从百度翻译开放平台来的啊 密钥也是 开通了通用翻译 但是翻译不了

**Comment by xxxml** [comment]
在 安卓系统中不能显示中文~
