### ISSUE TITLE
[Feature] Genre translation

### ISSUE THREAD

**Issue by lanslot6** [javtube/jellyfin-plugin-javtube#13]
### Description

- Add translation support for Genres
- Add backend caching for translations since the number of translation calls is going to be big

### Is this feature related to a specific bug?

No

### Do you have a specific solution in mind?

I can create PRs to do these if the backend is open sourced. Caching is not trivial to implement on the plugin side.

**Comment by xjasonlyu** [comment]
Thanks for the suggestion, but I don't think genres need to be actually translated.

I prefer to use a genres map/dict to convert them to desire language is relatively better. Thus, implementing this feature in the `OrganizeGenres` task seems to be a good way.

**Comment by xjasonlyu** [comment]
Actually, this feature can be done with the `SubstitutionTable` dict.

https://github.com/javtube/jellyfin-plugin-javtube/blob/a86dfdc3e26a256d94ac21a868bdef46a72c52e3/Jellyfin.Plugin.JavTube/Helpers/GenreHelper.cs#L9-L18

**Comment by xjasonlyu** [comment]
Check这个feature：[类型替换](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E7%B1%BB%E5%9E%8B%E6%9B%BF%E6%8D%A2)

因为类型比较固定，翻译还可能不准确，用替换表替代更好。

**Comment by xjasonlyu** [comment]
[`v2022.703.831.0`](https://github.com/javtube/jellyfin-plugin-javtube/releases/tag/v2022.703.831.0)已添加[类型替换](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E7%B1%BB%E5%9E%8B%E6%9B%BF%E6%8D%A2)功能，可以用于类型翻译转换。
