### ISSUE TITLE
[Feature] 添加数据源优先级排序

### ISSUE THREAD

**Issue by nokaka** [javtube/jellyfin-plugin-javtube#14]
### Description

根据图片质量，**自动排序**，或者添加**手动排序设置**。
因为有的数据源图片分辨率非常低，有的（比如AIRAV）则非常高。
手动识别可以自由选择，但自动识别好像只会选择第一个。
有时第一个源抓取不到图片，或者非常模糊。

![image](https://user-images.githubusercontent.com/101942715/175772906-ddedd6af-d75b-4f02-af4c-291f3fa6653e.png)

**Comment by xjasonlyu** [comment]
这是搜索时用的预览图，和实际刮削出来的图不一样，数据源优先级已经根据图片清晰度和资料完整度划分过了。

**Comment by nokaka** [comment]
但是似乎，抓取不到图片的问题是有的？有的手动识别是有图片的，其他信息也很全面，比如演员、演员图片、介绍等，但是自动识别，没有海报，只有缩略图。多次通过“扫描新的和有修改的文件”方式刷新元数据后，还是没有海报。
![image](https://user-images.githubusercontent.com/101942715/175773238-2ca024a3-736d-4812-a18c-c2e26be03baa.png)
![image](https://user-images.githubusercontent.com/101942715/175773241-3014777b-d94d-4bbf-8d8f-f7c47e565798.png)

**Comment by nokaka** [comment]
如果有其他问题，我会使用一段时间后再继续向你反馈，非常感谢！

**Comment by xjasonlyu** [comment]
> 但是似乎，抓取不到图片的问题是有的？自动识别后，其他信息也很全面，比如演员、演员图片、介绍等，但是自动识别，没有海报，只有缩略图。多次通过“扫描新的和有修改的文件”方式刷新元数据后，还是没有海报。
> 手动识别，能抓到图片，在手动选择后能抓到图片。演示如下。
> ![image](https://user-images.githubusercontent.com/101942715/175773238-2ca024a3-736d-4812-a18c-c2e26be03baa.png)
> ![image](https://user-images.githubusercontent.com/101942715/175773241-3014777b-d94d-4bbf-8d8f-f7c47e565798.png)
> ![image](https://user-images.githubusercontent.com/101942715/175773436-eee695d3-4112-49fb-b90b-13de2bf693d0.png)

这个问题没有遇到过，可能是你jellyfin的问题，我本地无法复现

**Comment by nokaka** [comment]
好的，我会使用一段时间后再继续向你反馈，非常感谢！
