### ISSUE TITLE
[Feature] 增加合集功能

### ISSUE THREAD

**Issue by maplejaw** [javtube/jellyfin-plugin-javtube#16]
### Description

之前用的JavScraper，会自动生成合集，感觉挺好用的，希望增加支持。
```c#
#if !__JELLYFIN__
            if (!string.IsNullOrWhiteSpace(m.Set))
                metadataResult.Item.AddCollection(m.Set);
#else
            metadataResult.Item.CollectionName = m.Set;
#endif
```

**Comment by xjasonlyu** [comment]
合集有什么用呢？

**Comment by maplejaw** [comment]
> 合集有什么用呢？

合集就是一个系列呀，方便收集控整理和观看这个系列的所有内容。

**Comment by xjasonlyu** [comment]
🤔奇怪，我当时用javscraper的时候咋不会出现合集啊，这个要怎么触发的吗。

**Comment by xjasonlyu** [comment]
而且添加这段代码似乎并不会出现合集。

```cs
#if !__JELLYFIN__
            if (!string.IsNullOrWhiteSpace(m.Set))
                metadataResult.Item.AddCollection(m.Set);
#else
            metadataResult.Item.CollectionName = m.Set;
#endif
```

**Comment by maplejaw** [comment]
emby实测是可以的，当同一个合集中有2个以上的视频，就会自动列出来。

**Comment by xjasonlyu** [comment]
我加了这段代码似乎没有效果。有点奇怪。

**Comment by xjasonlyu** [comment]
[Emby.JavTube@v2022.626.1556.0.zip](https://github.com/javtube/jellyfin-plugin-javtube/files/8986989/Emby.JavTube%40v2022.626.1556.0.zip)

这个编译版本里加了这段代码，你可以试试有没有合集出来，我本地是没有的。

**Comment by xjasonlyu** [comment]
> > [Emby.JavTube@v2022.626.1556.0.zip](https://github.com/javtube/jellyfin-plugin-javtube/files/8986989/Emby.JavTube%40v2022.626.1556.0.zip)
> > 这个编译版本里加了这段代码，你可以试试有没有合集出来，我本地是没有的。
> 
> 试了这个版本，可以自动识别合集了，感谢~

奇怪，可是我并没有效果🤔……

**Comment by xjasonlyu** [comment]
[`v2022.703.831.0`](https://github.com/javtube/jellyfin-plugin-javtube/releases/tag/v2022.703.831.0)已添加该功能。
