### ISSUE TITLE
[Bug] 一本道系列只能刮削元数据 图片数据不显示

### ISSUE THREAD

**Issue by zm19960501** [javtube/jellyfin-plugin-javtube#18]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

v2022.622.1459.0

### JavTube Server Version

4.7.5.0

### What OS are you seeing the problem on?

Windows

### Description

一本道系列只能刮削元数据  图片数据不显示   在媒体库已经勾选javtube刮削

**Comment by xjasonlyu** [comment]
麻烦Issue带上标题，然后提供emby日志，谢谢。

**Comment by xjasonlyu** [comment]
可能是你网络问题，我本地都是可以的。

你可以提供一下无法出现图片的番号，我再试试是不是插件的问题。
