### ISSUE TITLE
[Bug] 女优头像与电影电视剧明星头像资料相互污染

### ISSUE THREAD

**Issue by maxererer** [javtube/jellyfin-plugin-javtube#19]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.622.1459.0

### JavTube Server Version

2022.622.1459.0

### What OS are you seeing the problem on?

Other

### Description

使用群晖套件、emby，近期发现部分女优资料跟电影明星出现重合的现象，导致信息错误。
![3](https://user-images.githubusercontent.com/47648650/175856868-d3526cce-f223-4344-b5f1-524693a82106.png)
![2](https://user-images.githubusercontent.com/47648650/175856874-b6f3d44f-9b21-424f-bb48-7fe78ba248ae.png)
![123](https://user-images.githubusercontent.com/47648650/175856879-8ef41a60-b506-4357-a863-fa3d40840c56.png)
![4](https://user-images.githubusercontent.com/47648650/175856884-864ca580-64d8-4c13-b13d-2024673f2c75.png)
JULIA搜索也搜索不到，图像也不正确。

### Jellyfin/Emby Logs

[embyserver.txt](https://github.com/javtube/jellyfin-plugin-javtube/files/8988561/embyserver.txt)

**Comment by maxererer** [comment]
希望各位大佬指条明路，已经删了重装也不行。

**Comment by xjasonlyu** [comment]
麻烦Issue带上标题，谢谢。

这是Emby的问题，你有其他如tmdb插件开着的时候就会这样，暂时似乎没有办法。
