### ISSUE TITLE
[Bug] 缺少linux版的插件路径

### ISSUE THREAD

**Issue by JamesW99** [javtube/jellyfin-plugin-javtube#20]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

1.0.2

### JavTube Server Version

1.0.2

### What OS are you seeing the problem on?

Linux

### Description

https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E6%8F%92%E4%BB%B6%E5%AE%89%E8%A3%85

这个页面缺少linux版的插件路径

/var/lib/emby-server/plugins/

**Comment by xjasonlyu** [comment]
Added, thanks.
