### ISSUE TITLE
能否增加修改标题类型

### ISSUE THREAD

**Issue by lmhailong** [javtube/jellyfin-plugin-javtube#21]
### Description

标题基本是固定的，能否增加个修改标题类型的功能，比如我只想要番号，不要其他东西

**Comment by xjasonlyu** [comment]
可以考虑，但是应该必须强制带番号。

**Comment by xjasonlyu** [comment]
[`v2022.703.831.0`](https://github.com/javtube/jellyfin-plugin-javtube/releases/tag/v2022.703.831.0)已添加该功能。
