### ISSUE TITLE
[Bug] 中文字幕标签添加不上

### ISSUE THREAD

**Issue by 15064187978** [javtube/jellyfin-plugin-javtube#22]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

最新

### JavTube Server Version

最新

### What OS are you seeing the problem on?

Linux

### Description

[Bug] 中文字幕标签添加不上

**Comment by xjasonlyu** [comment]
计划任务运行了吗。

**Comment by 15064187978** [comment]
当然运行了，秒结束啊，一秒不到就结束

**Comment by xjasonlyu** [comment]
日志有什么结果吗，然后文件命名以及目录结构提供一下

**Comment by 15064187978** [comment]
- ### [](url)[](url)

**Comment by 15064187978** [comment]
在 2022-06-28 11:56:56，"Jason Lyu" ***@***.***> 写道：

日志有什么结果吗，然后文件命名以及目录结构提供一下

**Comment by 15064187978** [comment]
在 2022-06-28 11:56:56，"Jason Lyu" ***@***.***> 写道：

日志有什么结果吗，然后文件命名以及目录结构提供一下

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
embyserver.txt (38.77M, 2022年7月13日 12:05 到期)
下载

**Comment by 15064187978** [comment]
#
[Bug] 中文字幕标签添加不上
- [ ] 

> 

[ ] [](url) @

**Comment by xjasonlyu** [comment]
没有附件
