### ISSUE TITLE
[Feature] 识别或者说匹配有一些太激进

### ISSUE THREAD

**Issue by one-eeyed** [javtube/jellyfin-plugin-javtube#26]
### Description

我媒体库里基本是jav国产欧美混着塞，这样一些不是jav的也会被“强行”匹配上一个番号进行刮削

### Do you have a specific solution in mind?

能否加上一个像是exact match的规则选项开关，这样匹配不上的我再一个个修正就好了，不然匹配错的一时间也很难发现

**Comment by xjasonlyu** [comment]
首先你这样混放欧美与jav类型的电影就是不太常理的，正确的应该是jav 欧美 国产 分开媒体库放置。

其次，exact match 是很难做到的，比如有个文件名是abp00123或者mxgs-01，理论上应该可以匹配abp-123或 mxgs-0001，但是如果exact match就会失败。

**Comment by s0urcelab** [comment]
> 首先你这样混放欧美与jav类型的电影就是不太常理的，正确的应该是jav 欧美 国产 分开媒体库放置。
> 
> 其次，exact match 是很难做到的，比如有个文件名是abp00123或者mxgs-01，理论上应该可以匹配abp-123或 mxgs-0001，但是如果exact match就会失败。

我是分开的两个媒体库，但是javtube会刮削演员的数据，这个行为是跨媒体库的，所以我电影库里的演员很多被莫名其妙加上了jav的错误信息，我没有在jellyfin里找到控制的办法，有什么思路么？

**Comment by xjasonlyu** [comment]
这是jellyfin/emby都有的bug，目前没有好的解决方法。

我个人的做法是把正常电影和JAV分成两个服务端隔离。

**Comment by s0urcelab** [comment]
> 这是jellyfin/emby都有的bug，目前没有好的解决方法。
> 
> 我个人的做法是把正常电影和JAV分成两个服务端隔离。

部署两套jellyfin么？

**Comment by xjasonlyu** [comment]
是的

**Comment by s0urcelab** [comment]
> 是的

我去jellyfin那边提个issue好了，感觉这个问题还挺头疼的
