### ISSUE TITLE
[Feature] 请求Plex支持

### ISSUE THREAD

**Issue by beermedlar** [javtube/jellyfin-plugin-javtube#3]
### Description

请求支持plex插件搜刮

**Comment by xjasonlyu** [comment]
~~感觉Plex不太好用~~
~~而且也买不起Plex~~

**Comment by toyqiu** [comment]
如果 donate 一个 plex pass 的话有否可能支持

**Comment by xjasonlyu** [comment]
Plex似乎即将取消插件支持。

[Q：插件计划支持Plex吗？](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#q%E6%8F%92%E4%BB%B6%E8%AE%A1%E5%88%92%E6%94%AF%E6%8C%81plex%E5%90%97)

**Comment by nicholastz** [comment]
众筹一波上个Plex插件？
