### ISSUE TITLE
[Feature]  优化文件夹封面

### ISSUE THREAD

**Issue by stonejihub** [javtube/jellyfin-plugin-javtube#30]
### Description

由于bt下载的jav文件夹内常含有一两个 几十MB的广告视频比如uu34.mp4 。javtube会把这些广告视频也匹配封面，这个问题不大。但是这个文件夹的封面被设置为广告视频的封面而不是正确的jav封面。
比如这一行都是文件夹内包含广告视频，封面都是广告视频匹配到的封面
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/69335072/178294356-6ad777d8-fc83-4b17-822b-4271e5fa5a5b.png">
下图是上面第一个文件夹内的内容，JUL-106是正确的jav，ABP-933是广告匹配的封面
<img width="543" alt="image" src="https://user-images.githubusercontent.com/69335072/178294169-b141147f-7092-4fe5-8cf8-55ca518da86c.png">
我希望开发者能优化一下代码，使得文件夹的封面为JUL-106的封面

**Comment by xjasonlyu** [comment]
这是emby的行为，插件做不了，把广告视频删了就行。

**Comment by stonejihub** [comment]
感谢，了解。就是一个个删除广告视频有点麻烦。如果emby有过滤100MB以下视频的功能就好了
