### ISSUE TITLE
[Feature] 封面变成横板缩略图

### ISSUE THREAD

**Issue by CXYdgd** [javtube/jellyfin-plugin-javtube#32]
### Description

刚搜刮完之后一切正常非常完美，但是过一天左右后，竖版的封面变成了横板的缩略图显示，这是因为部分没有搜刮出poster竖版封面导致的吗？或者如何进行设置才能让竖版封面不被缩略图替换呢？

**Comment by xjasonlyu** [comment]
可以提供下你的媒体库刮削器配置吗，一共开了几个刮削器？

**Comment by CXYdgd** [comment]
![9DAB42DD-2E8C-4437-86E3-59E3C013C2C0](https://user-images.githubusercontent.com/50445442/179322443-708e3ce8-f481-4ee0-a739-01e52aec3065.png)
![E8E056B7-8E5A-4F92-976F-AE93DE45482A](https://user-
![A4E0EDEE-0732-45A1-8555-4B362C27B07F](https://user-images.githubusercontent.com/50445442/179322455-0448f2f8-065a-4524-87dc-af826f0dc5d1.png)
![F5479328-0A6A-4A4A-A1A3-1E2F9F6784D5](https://user-images.githubusercontent.com/50445442/179322457-76e4f2bc-22a9-4763-9f38-08eccfef6c73.png)
![94E93C7B-E162-4ADC-BA11-1307F038B7A4](https://user-images.githubusercontent.com/50445442/179322460-7575955e-4298-46a8-a7d4-b92201a89978.png)
![9DEB83AB-716C-44C7-83F4-57C621B71480](https://user-images.githubusercontent.com/50445442/179322462-35de9489-070e-48f1-95c7-759a7e8c187b.png)
![80F028E8-9B16-4CF6-AD47-47B2DA04444E](https://user-images.githubusercontent.com/50445442/179322463-8d3977a2-aad8-4aef-b22d-b4c603d09d43.png)
images.githubusercontent.com/50445442/179322452-568b7551-20c6-439b-846a-5b6afc17962e.png)
![2E3A804F-1376-466F-AE87-4590A5EC5087](https://user-images.githubusercontent.com/50445442/179322454-b58f3d51-6f25-4053-988b-bbf226558b0c.png)




> 可以为你的媒体库提供几个刮削器配置吗，一共查看刮削器？
> 
> 勾选JavTube的话，一般是不会出现危险的问题。

这是我的配置，只有javtube而且我尝试过把图像获取器-获取设置中的缩略图去掉，依然会刮削缩略图，最大的问题是，为什么明明已经刮削出封面，正常一段时间后却被缩略图替换

**Comment by CXYdgd** [comment]
![9DAB42DD-2E8C-4437-86E3-59E3C013C2C0](https://user-images.githubusercontent.com/50445442/179322443-708e3ce8-f481-4ee0-a739-01e52aec3065.png)
![E8E056B7-8E5A-4F92-976F-AE93DE45482A](https://user-
![A4E0EDEE-0732-45A1-8555-4B362C27B07F](https://user-images.githubusercontent.com/50445442/179322455-0448f2f8-065a-4524-87dc-af826f0dc5d1.png)
![F5479328-0A6A-4A4A-A1A3-1E2F9F6784D5](https://user-images.githubusercontent.com/50445442/179322457-76e4f2bc-22a9-4763-9f38-08eccfef6c73.png)
![94E93C7B-E162-4ADC-BA11-1307F038B7A4](https://user-images.githubusercontent.com/50445442/179322460-7575955e-4298-46a8-a7d4-b92201a89978.png)
![9DEB83AB-716C-44C7-83F4-57C621B71480](https://user-images.githubusercontent.com/50445442/179322462-35de9489-070e-48f1-95c7-759a7e8c187b.png)
![80F028E8-9B16-4CF6-AD47-47B2DA04444E](https://user-images.githubusercontent.com/50445442/179322463-8d3977a2-aad8-4aef-b22d-b4c603d09d43.png)
images.githubusercontent.com/50445442/179322452-568b7551-20c6-439b-846a-5b6afc17962e.png)
![2E3A804F-1376-466F-AE87-4590A5EC5087](https://user-images.githubusercontent.com/50445442/179322454-b58f3d51-6f25-4053-988b-bbf226558b0c.png)




> 可以为你的媒体库提供几个刮削器配置吗，一共查看刮削器？
> 
> 勾选JavTube的话，一般是不会出现危险的问题。

这是我的配置，只有javtube而且我尝试过把图像获取器-获取设置中的缩略图去掉，依然会刮削缩略图，最大的问题是，为什么明明已经刮削出封面，正常一段时间后却被缩略图替换

**Comment by CXYdgd** [comment]
> 

我的配置可以理解为只是修改了语言和地区，然后去掉所有刮削器勾选仅仅勾选javtube 然后去掉了字幕下载而已，其他应该都没动

**Comment by CXYdgd** [comment]
![2A2F6CFE-ED8B-4CC8-AEB8-D87AC73E6120](https://user-images.githubusercontent.com/50445442/179323499-dd707240-5856-4899-92fd-6de143411015.png)
![BCF64BE5-B93D-433E-85CD-D3C1330B2E5F](https://user-images.githubusercontent.com/50445442/179323503-c91d3f04-62b9-41a2-abdb-aba04390dfd9.png)
![C0C3461D-E393-4C24-A358-1CC7B9B48FEE](https://user-images.githubusercontent.com/50445442/179323508-976511af-0665-47aa-8013-43cac311972a.png)


> 可以提供下你的媒体库刮削器配置吗，一共开了几个刮削器？
> 
> 如果仅勾选JavTube的话，一般是不会出现这类问题的。

我在两台vps上都进行了这样的刮削，最终结果都变成了这个效果，在emby 上他会自动识别成横向缩略图变成封面，但是我用Filebox只支持竖版，就会很奇怪，我感觉这是Emby自身识别到部份影片没有刮削到竖版封面，就强制把横版缩略图替换竖版封面了？

**Comment by CXYdgd** [comment]
> 可以提供下你的媒体库刮削器配置吗，一共开了几个刮削器？
> 
> 如果仅勾选JavTube的话，一般是不会出现这类问题的。

第三方封面就成这样了
![Uploading 51689FD8-7D13-4570-AF81-35E74517E60A.png…]()

**Comment by CXYdgd** [comment]
> 可以提供下你的媒体库刮削器配置吗，一共查看几个刮削器？
> 
> 勾选JavTube的话，一般是不会出现危险的问题。

![2D136600-3325-4BDF-8D2A-79A187D694F6](https://user-images.githubusercontent.com/50445442/179323860-23e62c8e-7527-4e25-b15b-4fc0c59497d2.png)

第三方app封面只显示被裁剪的缩略图

**Comment by CXYdgd** [comment]
> 可以为你的媒体库提供几个刮削器配置吗，一共查看刮削器？
> 
> 勾选JavTube的话，一般是不会出现危险的问题。

如果暂时无法解决的话我尝试一下用另外一个刮削器？看看是否会有同样的问题，如果有同样的问题应该就说明是Emby自身的原因吧，我之前尝试过其他刮削器，但是刮削出来的封面很模糊，我就立马改成了咱们这个刮削器，没有保留一天以上

**Comment by CXYdgd** [comment]
> 可以为你的媒体库提供几个刮削器配置吗，一共查看刮削器？
> 
> 勾选JavTube的话，一般是不会出现危险的问题。

还有一点就是，无码的视频刮削出来却一直正常，他们唯一的区别是有码的量比较大，无码我目前仅仅放了一个月的影片测试

**Comment by xjasonlyu** [comment]
之前似乎也有人和你有类似的情况，但是造成原因不明。我是直接刷新元数据就好了。

**Comment by CXYdgd** [comment]
> 

我这边也是刷新数据就好了，但是过两天有，变了，我感觉是Emby为了美观的一个机制吧……

**Comment by luckyxyz1981** [comment]
看下emby的计划任务，看是不是有开启周期定时刮削的任务，如果你自己刮削的为准，可以关闭定时任务

**Comment by CXYdgd** [comment]
> 看下emby的计划任务，看是不是有开启周期定时刮削的任务，如果你自己刮削的为准，可以关闭定时任务

自己刮削和定时刮削的东西会有区别吗？总之谢谢，我试试

**Comment by kklod** [comment]
遇到了同样的问题

**Comment by CXYdgd** [comment]
> 

解决了，确实是封面刮削不到所以替代了比如KTRA系列很多刮不到，用另外一个插件一起刮削做备选就可以了，另外一个刮削器的封面分辨率比较低……希望以后能添加刮削源吧

**Comment by luckyxyz1981** [comment]
> > 
> 
> 解决了，确实是封面刮削不到所以替代了比如KTRA系列很多刮不到，用另外一个插件一起刮削做备选就可以了，另外一个刮削器的封面分辨率比较低……希望以后能添加刮削源吧

什么插件，借一步说话
