### ISSUE TITLE
找不到服务，是哪里设置错了吗，求大佬指教

### ISSUE THREAD

**Issue by misakamik0t0** [javtube/jellyfin-plugin-javtube#34]
### Description

MediaBrowser.Providers.Manager.ProviderManager: Provider "JavTube" failed to retrieve search results
System.Net.Http.HttpRequestException: Name or service not known (api.javtube.internal:443)

**Comment by xjasonlyu** [comment]
你服务器设置了吗，你用的是默认无效的服务器地址
