### ISSUE TITLE
jellyfin10.8插件无法运行

### ISSUE THREAD

**Issue by kivialv** [javtube/jellyfin-plugin-javtube#35]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.711.1150.0

### JavTube Server Version

v1.0.10

### What OS are you seeing the problem on?

Linux

### Description

![(E_G@U8WAF~XKJ%C$EV018P](https://user-images.githubusercontent.com/46437736/179702107-9698eebd-0a70-425c-ad82-a45e303a3d51.png)

**Comment by xjasonlyu** [comment]
Jellyfin版本需要为10.8.1及以上。
