### ISSUE TITLE
[Feature] 希望能加入刮削源配置选项

### ISSUE THREAD

**Issue by didu1203** [javtube/jellyfin-plugin-javtube#37]
### Description

自动刮削的时候不能选择首选的刮削源

**Comment by xjasonlyu** [comment]
你想要首选什么刮削源吗

**Comment by luckyxyz1981** [comment]
默认刮削结果没有演员表，然后要选择识别另外的源才能补完演员表

**Comment by xjasonlyu** [comment]
理论上是有的，fanza数据很全了，另外还有avwiki做补充

**Comment by fjiang423** [comment]
+1, 还有很多问题通过自定义刮削源，或者定义刮削源优先顺序可以解决， 比如：

默认源FANZA 识别的时候经常空缺演员，如老片子XV-827 ，新一点的如WANZ-593。标题，介绍，截图都能识别但是演员总是空缺，需要手动识别，选择如AVWIKI的源来补完。
有一些老片子像DVAJ-184，截图经常空缺不知道是不是FANZA的原因。希望插件或者后端可以在识别出片源但是截图，封面，演员空缺的时候可以选择备用源来补充
