### ISSUE TITLE
[Feature] 百度翻译不再免费了，有无替代品呢？

### ISSUE THREAD

**Issue by foreverlong** [javtube/jellyfin-plugin-javtube#38]
### Description

百度翻译不再免费了，有无替代品呢？

**Comment by CXYdgd** [comment]
同问，欠费67元😅

**Comment by Neurotoxin0** [comment]
现在免费版5万字/月，但是只要实名了就可以换成高级版的（免费），100万字/月，够用

**Comment by CXYdgd** [comment]
> 

不够的，我就实名了，欠费67元了已经

**Comment by Neurotoxin0** [comment]
> > 
> 
> 不够的，我就实名了，欠费67元了已经

你换成100万字的版本了嘛？？？？ 我前几天转到这个插件然后全部重新刮削了一遍才用了60万字，不太可能每个月都用得完把。。

**Comment by laowangdegit** [comment]
> > 
> 
> 不够的，我就实名了，欠费67元了已经

卧槽？今天刚开，这玩意超了是欠费？？我以为是自动停止，这谁敢开
