### ISSUE TITLE
[Bug] JELLYFIN无法刮削演员的人像图

### ISSUE THREAD

**Issue by 399294508** [javtube/jellyfin-plugin-javtube#4]
### Description

这个问题是什么情况呢

**Comment by xjasonlyu** [comment]
你需要提供更多的信息，其他人都是没这个问题的

**Comment by 399294508** [comment]
已经解决，设置有点问题，sorry

**Comment by kenthweb** [comment]
不好意思，我也遇到一樣的問題
![圖片](https://user-images.githubusercontent.com/76155824/175835249-61a88070-79f6-4fa9-a888-163c153cadd8.png)
演員圖像不會顯示(或說是顯示空白)
請問您是如何解決的

**Comment by xjasonlyu** [comment]
是就偶尔几个，还是全都是这样？
