### ISSUE TITLE
[Bug] 海报不正确有杂项

### ISSUE THREAD

**Issue by CXYdgd** [javtube/jellyfin-plugin-javtube#40]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

7.19最新版

### JavTube Server Version

最新版

### What OS are you seeing the problem on?

Linux

### Description

海报不正确导致默认海报错误
![Uploading 50F321A7-A5B0-4117-815B-47BEAE377523.png…]()

**Comment by CXYdgd** [comment]
![Uploading 2BB9BEDF-B7C7-4E54-817A-56A9A9475447.png…]()

**Comment by CXYdgd** [comment]
![3124129E-36F3-4E1C-A3CB-B5497B77C016](https://user-images.githubusercontent.com/50445442/181903165-35e091e9-e504-4aae-987f-30e4f1ecbcf8.png)

**Comment by xjasonlyu** [comment]
这不是bug，因为某些番号用的封面大图不是常规ABC面，很难去裁切。

**Comment by CXYdgd** [comment]
> 

好的吧，希望这种不多，直接手动改了
