### ISSUE TITLE
[Feature] 强烈催一下 开发者增加 字幕标签！！！！

### ISSUE THREAD

**Issue by jeron-lgy** [javtube/jellyfin-plugin-javtube#43]
### Description

强烈催一下 开发者增加 字幕标签！！！！

**Comment by xjasonlyu** [comment]
什么是字幕标签

**Comment by Neurotoxin0** [comment]
我觉得他说的就是这种tag吧 #39 
我看旧的JAV插件里有这种，如果有中文字幕就加Genre标签: -C

**Comment by jeron-lgy** [comment]
![image](https://user-images.githubusercontent.com/77041127/183097891-eecae243-e2cd-4fb3-bea7-2ac480f8977f.png)
其实就是这种 但是今天发现 同样命名-c的 有的就有标签 有的就没有 不知道为什么

**Comment by laowangdegit** [comment]
这算是水印吧，另外有一个项目https://github.com/yoshiko2/AV_Data_Capture有这个水印功能，可以添加流出，字幕等等的水印，作者可以参考一下

**Comment by xjasonlyu** [comment]
不是一个原理的，插件端做这个比较复杂。

**Comment by jeron-lgy** [comment]
> 这算是水印吧，另外有一个项目[https://github.com/yoshiko2/AV_Data_Capture有这个水印功能，可以添加流出，字幕等等的水印，作者可以参考一下](https://github.com/yoshiko2/AV_Data_Capture%E6%9C%89%E8%BF%99%E4%B8%AA%E6%B0%B4%E5%8D%B0%E5%8A%9F%E8%83%BD%EF%BC%8C%E5%8F%AF%E4%BB%A5%E6%B7%BB%E5%8A%A0%E6%B5%81%E5%87%BA%EF%BC%8C%E5%AD%97%E5%B9%95%E7%AD%89%E7%AD%89%E7%9A%84%E6%B0%B4%E5%8D%B0%EF%BC%8C%E4%BD%9C%E8%80%85%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E4%B8%80%E4%B8%8B)

对对对 之前就用这个用过好长时间
