### ISSUE TITLE
[Bug] 部分影片识别不到就会乱选一个进行刮削

### ISSUE THREAD

**Issue by Neurotoxin0** [javtube/jellyfin-plugin-javtube#47]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] #48

### JavTube Plugin Version

latest

### JavTube Server Version

latest

### Description

例如KVR2012-47, KVR1707-5 这种搜不到的影片，在刮削时db会随机返回番号并且强行刮削；

尝试手动识别后依旧随机返回，并且每次识别返回值都不一样 -> 好像会随机选择server db里的缓存， 并且有可能和最后查询的条目有关（我的最后查询为NHD-001/NHD-002，第一次手动识别中存在相同内容，但不确定，例图见图二/三）

图一：自动刮削结果
![自动刮削](https://user-images.githubusercontent.com/32124086/182670123-e4467368-9f5c-4805-858b-12df548cb3fa.jpg)

图二/三：手动识别结果
![手动识别1](https://user-images.githubusercontent.com/32124086/182670511-8df4128d-4740-4031-9070-0cf9f2f72a54.jpg)
![手动识别2](https://user-images.githubusercontent.com/32124086/182670522-021a0d1c-1337-4650-a7a9-338a0fd4415d.jpg)

图三：真实番号
![真实番号](https://user-images.githubusercontent.com/32124086/182670530-5b82cec9-741f-4b18-9ffb-575325d2234b.jpg)

**Comment by xjasonlyu** [comment]
是可能存在这种情况，目前最好的办法还是手动识别一下。

图片是都可以显示的，不能显示图片通常为本地问题。

**Comment by Neurotoxin0** [comment]
加了个反代可以显示图片，但是返回值和真实番号搭不上边

建议可能把不能准确识别的影片搁置？ 就是不进行处理，不强制刮削，这样的话一眼看过去发现没有图片的就知道是无法识别的了，现在强制刮削的话就无法快速判断是否是无法识别的影片了（要不是又连续四个一样番号一样图片的影片紧挨在一起我也不会发现这问题x）

**Comment by CrazyShipOne** [comment]
+1 有时候可能会国产日本放在一个文件夹里了，国产少部分没有刮削，大部分都是识别错误的。也是因为好多番号连在一起发现的。。

**Comment by Neurotoxin0** [comment]
补充一下，

现在准确识别率以及降到10%左右了，同时加入十个新影片，并且标题内番号清晰，但10个里面9个自动刮削下来都是错误番号的影片，必须要人工进去点识别才能纠正

 - 影片的名称：[XXX-XXX] XXXXXXX; 括号里是番号，后面跟着标题，server日志能看到查询了正确的标题，但是返回的却是错误的影片信息
 - Jav Server端缓存没丢过，尝试删除缓存并重启， 不能解决问题

**Comment by xjasonlyu** [comment]
并不存在这种问题…

**Comment by Neurotoxin0** [comment]
我都测了50几部片子了，一半以上是错的。。何来不存在？

图片一一对应，图一是准确番号，图二是自动识别的番号
--
![image](https://user-images.githubusercontent.com/32124086/189502273-57f72ec1-72e1-4764-bd24-b63a2b6b0d27.png)
![image](https://user-images.githubusercontent.com/32124086/189502293-c1d2f682-8fa7-4be3-965d-801b6e960d92.png)
--

--
![image](https://user-images.githubusercontent.com/32124086/189502302-5f8a7273-e8af-4d25-859a-54ccfb898bed.png)
![image](https://user-images.githubusercontent.com/32124086/189502304-5e4cd018-a2e0-455a-9d69-c8142c12f8cf.png)
--

--
![image](https://user-images.githubusercontent.com/32124086/189502312-05e43631-1a1e-4360-a204-436af976c93c.png)
![image](https://user-images.githubusercontent.com/32124086/189502316-86895109-5784-446d-b9cd-dccfef3a4bc2.png)
--

**Comment by Neurotoxin0** [comment]
再补一张图，光是刚刚放进去的8个片子里就一个是自动准确识别的
![image](https://user-images.githubusercontent.com/32124086/189502349-5dea3b84-53e1-474f-a915-e4d59e5c9d1d.png)

**Comment by Neurotoxin0** [comment]
前后端截图如下
--
源文件名（带准确番号）
![image](https://user-images.githubusercontent.com/32124086/189502582-2f573bfb-ae8d-40c0-963a-261c642ead85.png)
--

--
后端收到的番号
![image](https://user-images.githubusercontent.com/32124086/189502618-b8652973-dd17-466b-baef-3c78223596bd.png)
--

--
自动识别后结果
![image](https://user-images.githubusercontent.com/32124086/189502636-aeaf8d02-c906-479b-8b00-e1f67163f3a7.png)
--

可以看出从前端插件给到后端的时候就已经出错了，后端正常返回而已

**Comment by xjasonlyu** [comment]
你用`[XXX-123] YYYYY`这样的方式命名影片是不推荐的。

**Comment by Ador-able** [comment]
> 是可能存在这种情况，目前最好的办法还是手动识别一下。
> 
> 图片是都可以显示的，不能显示图片通常为本地问题。

有一些就是查询不到的番号，手动识别返回的结果也全部都是错误的。元数据数据由于都是错误的，修改的话需要手动一个个的改很繁琐，能不能提个建议：当文件名包含unknown字样时，返回的源数据就是文件名，图像的话可以像Screen Grabber一样返回视频中的一个截图。
