### ISSUE TITLE
[Feature] 建议后端找不到返回404

### ISSUE THREAD

**Issue by jj99889** [javtube/jellyfin-plugin-javtube#5]
### Description

Currently, the backend would return http code 500 when movie could not be found. This would trigger an HttpRequest exception in the Jellyfin environment. I would suggest it would be more appropriate to return a 404 in this case?

**Comment by xjasonlyu** [comment]
返回404和500都会产生exception，这对jellyfin没什么影响吧，因为就是搜不到？
