### ISSUE TITLE
[Feature] 我看推荐的群辉安装博客里，翻译是有所有翻译的，我2022.719.1120.0插件怎么不能翻译标签

### ISSUE THREAD

**Issue by laowangdegit** [javtube/jellyfin-plugin-javtube#50]
### Description

我看推荐的群辉安装博客里，翻译是有所有翻译的，我2022.719.1120.0插件怎么不能翻译标签，后来看到有字符替换功能，但感觉不是长久之计，能直接翻译吗

**Comment by xjasonlyu** [comment]
标签不用翻译，都是固定的厂商工作室啥的，没有翻译的意义。

**Comment by laowangdegit** [comment]
请问有办法显示演员中文名吗，比如先获取到元数据和演员照片，然后翻译一下演员名，把照片的信息改成翻译出来的名字。有些演员名字纯片甲的，很难受
