### ISSUE TITLE
[Feature] 显示演员中文名

### ISSUE THREAD

**Issue by xjasonlyu** [javtube/jellyfin-plugin-javtube#51]
请问有办法显示演员中文名吗，比如先获取到元数据和演员照片，然后翻译一下演员名，把照片的信息改成翻译出来的名字。有些演员名字纯片甲的，很难受

_Originally posted by @laowangdegit in https://github.com/javtube/jellyfin-plugin-javtube/issues/50#issuecomment-1210673958_

**Comment by xjasonlyu** [comment]
插件配置页面，用演员名替换把日文名替换成中文即可。

不过需要注意中文名可能导致搜索不到部分演员照片。

**Comment by laowangdegit** [comment]
![image](https://user-images.githubusercontent.com/110841992/183915481-1360668b-832a-4622-9389-08b11336a4bb.png)
这个标题的演员名字能打个空格隔开吗，但我怀疑这是元数据的标题里自带的演员名，我是默认设置，有的标题里就不带演员名
