### ISSUE TITLE
[Documentation] Jellyfin插件安装教程缺server描述

### ISSUE THREAD

**Issue by skret028** [javtube/jellyfin-plugin-javtube#59]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

v2022.905.1521.0

### JavTube Server Version

v2022.905.1521.0

### Description

Jellyfin的插件配置里，server的url没有描述，默认填的是https://
实际上应该是http://ip:8080/

**Comment by xjasonlyu** [comment]
这个不需要描述的吧，你部署的是纯http服务端就写`http://`，你加了https就写`https://`喽。

**Comment by skret028** [comment]
> 这个不需要描述的吧，你部署的是纯http服务端就写`http://`，你加了https就写`https://`喽。

Wiki应该是从零说明吧，我装的docker，变量里没有配置http或是https，只有端口配置。
插件里这个配置的描述是：HTTP url of JavTube Server. 但默认填写的是https://
存在一定歧义，需要试错几分钟。
其他参数都有说明，唯独最主要的没有在wiki中体现，个人觉得可以加上。

**Comment by hwadong860** [comment]
> > 这个不需要描述的吧，你部署的是纯http服务端就写`http://`，你加了https就写`https://`喽。
> 
> Wiki应该是从零说明吧，我装的docker，变量里没有配置http或是https，只有端口配置。 插件里这个配置的描述是：HTTP url of JavTube Server. 但默认填写的是https:// 存在一定歧义，需要试错几分钟。 其他参数都有说明，唯独最主要的没有在wiki中体现，个人觉得可以加上。

http还是https，看的是你服务端有没有SSL签证。也就是说你服务端可以https访问，你就填https，否则http…
