### ISSUE TITLE
[Feature] 无法建立和后端的连接，人都整麻了

### ISSUE THREAD

**Issue by xmasrain** [javtube/jellyfin-plugin-javtube#63]
### Description

![image](https://user-images.githubusercontent.com/58833842/190707723-40b899a4-dfa4-46d9-bb30-dc113eabd56d.png)
![image](https://user-images.githubusercontent.com/58833842/190707791-71c60fce-2ed6-4eef-bd62-f5d5eadcfd9b.png)
![image](https://user-images.githubusercontent.com/58833842/190708008-c501a9b8-5140-47a1-b02f-d7e97c886da4.png)

如图所示，建立了后端，填写相应的地址和端口，可就是不能建立通讯，不知道问题出在哪？？？

**Comment by xjasonlyu** [comment]
可能是你docker端口没打开，或者其他连接过去的问题，总之是网络连接哪里没配置好。

**Comment by xmasrain** [comment]
javtube在容器内一定要使用8080端口吗？

**Comment by xmasrain** [comment]
怎么用-port参数修改默认端口？

**Comment by xjasonlyu** [comment]
加个PORT环境变量就行了

**Comment by xmasrain** [comment]
> 加个PORT环境变量就行了

问题解决了，加了port变量，改了被占用的端口就好了。
有个新问题：该插件能否只用来为jellyfin添加艺人头像？因为我已经在本地刮削过所有影片了，只是艺人头像无法正常显示。所以想问有没有单独的艺人头像功能使用。

**Comment by xjasonlyu** [comment]
想这样的话，你只需要在你的媒体库禁用这个插件就行了。因为演员头像它是自动调用插件搜刮的。

**Comment by xmasrain** [comment]
> 想这样的话，你只需要在你的媒体库禁用这个插件就行了。因为演员头像它是自动调用插件搜刮的。

感谢，建议写入帮助说明中~
