### ISSUE TITLE
[Feature] 建议添加排除小文件的功能，部分例如广告非影片也会乱选一个进行刮削 

### ISSUE THREAD

**Issue by finch-ift** [javtube/jellyfin-plugin-javtube#64]
### Description

刮的时候把很多非影片资源也进行了刮削，特别是广告，建议添加不刮削小文件的选项：例如小于5分钟或小于200MB的文件忽略

**Comment by xjasonlyu** [comment]
这个不好实现，因为一方面emby API只会给你文件名，而不知道他的具体位置以及文件大小视频时长，另一方面，资料库里就不应该会有广告文件吧，应该手动整理掉的。
