### ISSUE TITLE
[Feature] 曾刮削成功的影片现无法刮削，且精准URL搜索失败

### ISSUE THREAD

**Issue by xwt961125** [javtube/jellyfin-plugin-javtube#66]
### Description

    原使用[v2022.905.1521.0]版本一切正常，未遇到过不能刮削的影片。
    在未改变插件及后端设置的情况下，部分原先已经有元数据的影片在试图更换刮削源的时候发现刮削不到任何信息，尝试使用精准ID搜索和精准URL搜索均失效，且确认刮削源网站存在影片信息。
    元数据为上次成功刮削所得，尝试直接复制Javtube ID再次刮削，无任何内容显示。
    现更新插件及后端至最新版本，并尝试开启代理均无效果。

**Comment by xjasonlyu** [comment]
番号或者链接给一个？

**Comment by xwt961125** [comment]
011109_507
Javtube ID：JavBus:011109_507
URL：https://www.javbus.com/011109_507

**Comment by xjasonlyu** [comment]
可能是你这边刮削配置之类的问题，我都是没问题的

![264EFDA7-3AD6-4E91-AF6C-41D06A3DBBF7](https://user-images.githubusercontent.com/28824352/191657534-65adb34a-092a-4d0c-b1ab-cc96c48cb00b.jpeg)

你是不是开了provider filter？

**Comment by xwt961125** [comment]
感谢，找到问题了，我这边javbus和1pondo都刮削不到= =
arazon和avwiki的还在
可能是一次性刮了一百多部被ban了？
我再尝试一下更换代理

**Comment by xwt961125** [comment]
后端放到了koyeb上，一切恢复正常，可能真的是被ban了？_(:з」∠)_
