### ISSUE TITLE
[Feature] ARZON的图片加载不出来，信息都是正常的，如果要配置代理有简单教程吗？

### ISSUE THREAD

**Issue by ddddalex** [javtube/jellyfin-plugin-javtube#67]
### Description

之前用群晖docker配置的后端运行正常，今天ARZON刮削源的图片加载不出来了，想研究代理。群晖docker已经配置好了clash的代理容器，怎么让刮削器后端通过这个容器进行代理刮削呢？

**Comment by ddddalex** [comment]
如果可以在插件配置界面直接配置代理就好了

**Comment by xjasonlyu** [comment]
没有，图片是后端下载的，你要给后端配置代理才可以。

**Comment by ddddalex** [comment]
后端的设置环境变量实在没搞懂，是不是在创建容器的时候就加上-e命令。我这在putty上试了下命令，可以成功创建，但是运行的时候显示-e
flag未被定义，感觉是不是什么操作语言没有下载。求教


Jason Lyu ***@***.***> 于2022年9月24日周六 16:52写道：
