### ISSUE TITLE
10.8的jellyfin 搜索不到插件

### ISSUE THREAD

**Issue by Tarzanc** [javtube/jellyfin-plugin-javtube#7]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

最新

### JavTube Server Version

10.8

### What OS are you seeing the problem on?

Other

### Description

用的最新的储存库https://[raw.githubusercontent.com](https://raw.githubusercontent.com/javtube/jellyfin-plugin-javtube/dist/manifest.json)/javtube/jellyfin-plugin-javtube/dist/manifest.json

**Comment by xjasonlyu** [comment]
你哪里弄错了吧，我10.8是能搜到的。

**Comment by Tarzanc** [comment]
> 你哪里弄错了吧，我10.8是能搜到的。
和没有挂梯子有关系吗，我直接裸连的

**Comment by Tarzanc** [comment]
之前装了插件，后来我重置了jellyfin难道是没删干净

**Comment by xjasonlyu** [comment]
直连可能上不去的

**Comment by yellowspeedracer** [comment]
> 之前装了插件，后来我重置了jellyfin难道是没删干净

解决了吗？

**Comment by marsioc** [comment]
我也找不到...docker里面装的jellyfin，装上插件之后目录里面没找到

**Comment by NothingNA** [comment]
+1 群晖社群版 10.8 jellyfin 搜不到插件……只好换回emby了……

**Comment by bbllmaster** [comment]
raspi4 安装docker 版jellyfin，也有此问题

**Comment by xjasonlyu** [comment]
升到10.8.1了吗

**Comment by li-guohao** [comment]
搜不到的，可以尝试手动安装
