### ISSUE TITLE
[Bug] FSDSS系列番号刮削不对

### ISSUE THREAD

**Issue by ddddalex** [javtube/jellyfin-plugin-javtube#75]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

v2022.920.850.0

### JavTube Server Version

v2022.920.850.0

### What OS are you seeing the problem on?

Other

### Description

FSDSS-503这个番号刮削成KNAM-003，而且手动刮削没有正确的番号信息

**Comment by xjasonlyu** [comment]
这部都没上架吧
