### ISSUE TITLE
[Bug] 300MIUM-805无法刮捎

### ISSUE THREAD

**Issue by yuanzhongfei2022** [javtube/jellyfin-plugin-javtube#76]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

v2022.920.850.0

### JavTube Server Version

v1.0.21

### What OS are you seeing the problem on?

Windows

### Description

如题：300MIUM-805无法刮捎，
在Javbus上面是能搜索到的，但是在EMBY里面无法识别到。
300MIUM系列的均不能搜索到。

### JavTube Server

300MIUM

**Comment by xjasonlyu** [comment]
为什么是JavBus搜，首选不应该是MGS么。

**Comment by yuanzhongfei2022** [comment]
> 为什么是JavBus搜，首选不应该是MGS么。

现在是用这个插件，在EMBY里面无法搜到300MIUM系列的。

**Comment by xjasonlyu** [comment]
搜得出来的，你可能哪里配置错了吧。

![30A64CE8-7A36-4AA1-8D76-936D19F9500D](https://user-images.githubusercontent.com/28824352/194709603-70007846-f2f2-47df-ae96-b04c808f3446.jpeg)

**Comment by yuanzhongfei2022** [comment]
> 



> 为什么是JavBus搜，首选不应该是MGS么。



> 搜得出来的，你可能哪里配置错了吧。
> 
> ![30A64CE8-7A36-4AA1-8D76-936D19F9500D](https://user-images.githubusercontent.com/28824352/194709603-70007846-f2f2-47df-ae96-b04c808f3446.jpeg)

好的，我在检测下，哪里的问题
谢谢

**Comment by heizcode** [comment]
楼主，您这边处理了嘛？我也有遇到同样的问题，素人基本上都不能刮削出来（windows，emby）
