### ISSUE TITLE
后端反向代理

### ISSUE THREAD

**Issue by sifacaii** [javtube/jellyfin-plugin-javtube#79]
### Description

后端是否支持反向代理，我用Caddy反向代理无法刮削。

**Comment by xjasonlyu** [comment]
当然支持反代，我服务端就是caddy反代的。看看是哪里没有配置好吧。

**Comment by sifacaii** [comment]
`
:80 :443
proxy /javtube 127.0.0.1:39080 {
        without /javtube
}
`

我是这样设置的，用浏览器直接访问没问题，刮削不行。

**Comment by s0urcelab** [comment]
> `:80 :443` `proxy /javtube 127.0.0.1:39080 {` ` without /javtube` `}`
> 
> 我是这样设置的，用浏览器直接访问没问题，刮削不行。 你是怎么设置的。

我实测结果是反代不能有path，只能反代到根路径下面，例如example.com:39080 => example.com，不能example.com:39080 => example.com/javtube
带path会导致插件里出错，但是我没法debug

**Comment by xjasonlyu** [comment]
嗯对，插件上就是这么设计的。子路径暂时不能被反代。
