### ISSUE TITLE
[Bug] 对于已经存在元数据的视频刮削错误

### ISSUE THREAD

**Issue by ll789899** [javtube/jellyfin-plugin-javtube#8]
### JavTube Plugin Version

latest

### JavTube Server Version

latest

### What OS are you seeing the problem on?

Ubuntu

### Description

之前用javscraper刮削后 我重新换javtube刮削 但是刮削内容为空 看日志似乎是将老的元数据里的标题用作search而不是用文件名
另外，这种情况似乎只出现与MGS类型视频 正常英文开头的番即使存在老的元数据也能成功刮削
1、老的元数据
![image](https://user-images.githubusercontent.com/45455546/173244103-8d2991f2-d8ee-4eba-90c4-eb21917d5536.png)
2、文件名
![image](https://user-images.githubusercontent.com/45455546/173244169-5aed75fc-25ed-4c8a-94e5-460408e03421.png)
3、刮削日志
![image](https://user-images.githubusercontent.com/45455546/173244094-38b653cc-a1e0-4841-b6d2-27368b2336e3.png)

**Comment by UnsignedMe** [comment]
是有这个问题，我是删库重新刮削

**Comment by ll789899** [comment]
> 是有这个问题，我是删库重新刮削

确实也是个解决办法😂

**Comment by peny911** [comment]
> 是有这个问题，我是删库重新刮削

大佬，如何删库？

**Comment by xjasonlyu** [comment]
> > 是有这个问题，我是删库重新刮削
> 
> 大佬，如何删库？

把媒体库删了就行了啊。
