### ISSUE TITLE
[Bug] 后缀-C的影片未添加“中文字幕”tag

### ISSUE THREAD

**Issue by s0urcelab** [javtube/jellyfin-plugin-javtube#9]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

2022.609.1543.0

### JavTube Server Version

javtube/javtube-server:dev (sha256:98372caea90a95b2c72b67736273882a25e1b9dd319caf5ad19d2d3e795f7878)

### What OS are you seeing the problem on?

Windows

### Description

刮削成功但没有添加中文字幕tag

### JavTube Server

default

### Jellyfin/Emby Logs

[2022-06-13 16:10:20.817 +08:00] [INF] [9] Jellyfin.Plugin.JavTube.Providers.MovieProvider: Search for movie: "NACR-442-C"
[2022-06-13 16:10:23.781 +08:00] [INF] [17] Jellyfin.Plugin.JavTube.Providers.MovieProvider: Get movie info: "FANZA:h_237nacr00442"

**Comment by xjasonlyu** [comment]
看Wiki的PS：https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E4%B8%AD%E6%96%87%E5%AD%97%E5%B9%95

**Comment by s0urcelab** [comment]
不好意思，之前没看到PS

顺便可以增加下对中文字幕的判定规则么？
目前网上下载到的中文字幕影片名称常见的有xxx-c, xxx-ch, xxxch, xxx_ch（c和ch大/小写）这几种

**Comment by xjasonlyu** [comment]
可是可以，但是主流的都是-C结尾的，-ch之类的用的比较少

**Comment by s0urcelab** [comment]
> 可是可以，但是主流的都是-C结尾的，-ch之类的用的比较少

现在新出的资源可能-c居多，原先老的资源很多-ch的，原先用过一个本地运行的刮削器，它是支持-ch的，现在换成插件之后，我手动改了20多个文件名

**Comment by kid0613** [comment]
可以搭板問一下怎麼確定Javtube server端架設完成？

**Comment by xjasonlyu** [comment]
> > 可是可以，但是主流的都是-C结尾的，-ch之类的用的比较少
> 
> 现在新出的资源可能-c居多，原先老的资源很多-ch的，原先用过一个本地运行的刮削器，它是支持-ch的，现在换成插件之后，我手动改了20多个文件名

OK，我考虑一下。

**Comment by s0urcelab** [comment]
谢谢

**Comment by xjasonlyu** [comment]
已支持ch后缀中文字幕标签
