### ISSUE TITLE
[Bug]  wiki is gone？

### ISSUE THREAD

**Issue by TanY0Y0** [javtube/jellyfin-plugin-javtube#98]
### Verify steps

- [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
- [X] I have read the [Wiki](https://github.com/javtube/jellyfin-plugin-javtube/wiki), especially the [FAQ](https://github.com/javtube/jellyfin-plugin-javtube/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) page.
- [X] I have searched on the [issue tracker](……/) for a related issue.

### JavTube Plugin Version

x

### JavTube Server Version

x

### Description

what is happened with wiki and other help pages ？these are helpful for me，i really need these user guide

**Comment by xjasonlyu** [comment]
Fixed

**Comment by bebestmaple** [comment]
its gone now again.

**Comment by zenxds** [comment]
> Fixed

it's gone again.
